- hosts : remote 
  gather_facts: true 
  vars  : 
    - name: package
      prompt: "quel paquet voulez-vous installer "
      private: no

    - name : version 
      prompt: "quelle version du paquet?"
      private: no
      
  tasks:
    - name : install chosen package 
      apt: 
        package : "{{ package }}"
        version : "{{ version }}"