- hosts : remote 
  gather_facts: false
  vars  : 
      src: test.txt
      dest: /home/ansible_user/test.txt
      
  tasks:
    - name : copy fille to remote server 
      copy:
        src : "{{ src }}"
        dest: "{{ dest }}"